import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Zane's Dev Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          className="w-screen h-screen"
          style={{ backgroundColor: "#fffdf7" }}
        >
          <div className="h-24">
            <NavBar />
          </div>
          <div className="h-[calc(100vh-6rem)]">{children}</div>
          <div className="h-24">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
